services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge
      POSTGRES_DB: model_registry
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
